### ISSUE TITLE
TypeError: Converting circular structure to JSON and tus error

### ISSUE THREAD

**Issue by arturi** [transloadit/uppy-server#45]
Getting multiple errors sometimes when trying to re-upload a remote file:

1. Circular structure to JSON, we should probably use a more safe JSON parser, like this one: https://github.com/jed/lave.
2. `Error: tus: unexpected response while creating upload, originated from request (response code: 400, response text:` — this is the main issue.

Log:

```js
{ action: 'success',
  payload: 
   { complete: true,
     url: 'http://master.tus.io/files/e1afd9ca33fcb15c9092144d1a572096' } }
140795 140795 '100.00%'
{ action: 'success',
  payload: 
   { complete: true,
     url: 'http://master.tus.io/files/07f4d15fe523fe0bfb24ea5399c61f04' } }
::1 - - [28/Dec/2017:21:23:52 +0000] "OPTIONS /instagram/get/1636400252659303992_104680?carousel_id=2 HTTP/1.1" 200 13 "http://localhost:3452/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36"
uppy-server: Found an handler for request.
uppy-server: Instantiating uploader.
uppy-server: Waiting for socket connection before beginning remote download.
::1 - - [28/Dec/2017:21:23:52 +0000] "POST /instagram/get/1636400252659303992_104680?carousel_id=2 HTTP/1.1" 200 48 "http://localhost:3452/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36"
uppy-server: Socket connection received. Starting remote download.
[nodemon] files triggering change check: output/f12038b9-f8c1-450f-8fab-be80eeaf1f8c-1636400252659303992_104680
[nodemon] changes after filters (before/after): 1/0
{ action: 'error',
  payload: 
   { error: 
      { Error: tus: unexpected response while creating upload, originated from request (response code: 400, response text: )
          at DetailedError.Error (native)
          at new DetailedError (/uppy-server/node_modules/tus-js-client/lib.es5/error.js:23:87)
          at Upload._emitXhrError (/uppy-server/node_modules/tus-js-client/lib.es5/upload.js:236:23)
          at Request.xhr.onload (/uppy-server/node_modules/tus-js-client/lib.es5/upload.js:326:18)
          at ClientRequest.<anonymous> (/uppy-server/node_modules/tus-js-client/lib.es5/node/request.js:83:15)
          at emitOne (events.js:96:13)
          at ClientRequest.emit (events.js:188:7)
          at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
          at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
          at Socket.socketOnData (_http_client.js:363:20) originalRequest: [Object], causingError: null } } }
/uppy-server/src/uppy.js:92
      ws.send(JSON.stringify(data), (err) => {
                   ^

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at EventEmitter.sendProgress (/uppy-server/src/uppy.js:92:20)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Uploader.emitError (/uppy-server/src/server/Uploader.js:149:13)
    at Object.onError (/uppy-server/src/server/Uploader.js:170:18)
    at Upload._emitError (/uppy-server/node_modules/tus-js-client/lib.es5/upload.js:242:22)
    at Upload._emitXhrError (/uppy-server/node_modules/tus-js-client/lib.es5/upload.js:236:12)
    at Request.xhr.onload (/uppy-server/node_modules/tus-js-client/lib.es5/upload.js:326:18)
    at ClientRequest.<anonymous> (/uppy-server/node_modules/tus-js-client/lib.es5/node/request.js:83:15)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Acconut** [comment]
> Error: tus: unexpected response while creating upload, originated from request (response code: 400, response text: — this is the main issue.

We had some issues with the master.tus.io instance while it has been moved to a Kubernetes setup. However, these problems should be resolved now. Does this problem this arise?

**Comment by arturi** [comment]
Yeah, could be that, I will check again and let you know.

**Comment by arturi** [comment]
Got exact same error now with the following local storage:

<img width="1186" alt="screen shot 2018-01-05 at 4 31 44 pm" src="https://user-images.githubusercontent.com/1199054/34629412-03f0a84c-f236-11e7-94d7-bc7d8a3ebff5.png">

(might still be http vs https)

Uppy Server crashes, so no error on the client:

<img width="851" alt="screen shot 2018-01-05 at 4 35 16 pm" src="https://user-images.githubusercontent.com/1199054/34629549-83edefbe-f236-11e7-9b70-d728c1220a1e.png">

**Comment by ifedapoolarewaju** [comment]
> - Circular structure to JSON, we should probably use a more safe JSON parser, like this one: https://github.com/jed/lave.

I have fix this issue [here](https://github.com/transloadit/uppy-server/commit/e238b442cbcf9d3ecc62cd4ef6dded77c593da7e)



>Error: tus: unexpected response while creating upload, originated from request (response code: 400, response text: — this is the main issue.

Testing this from my end, it seemed to be the `http` vs `https` issue with `master.tus.io`.

I am closing this issue at this point. Please re-open if you feel a reason to 🙂
